name: CI to node aplication
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node-version: [16.x]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js in ${{ matrix.os }}
        uses: actions/setup-node@v3
      - run: npm ci
      - run: npm test
